export type ThemeMode = "light" | "dark";

export interface ThemeColors {
  background: string;
  foreground: string;
  primary: string;
  primaryForeground: string;
  secondary: string;
  secondaryForeground: string;
  muted: string;
  mutedForeground: string;
  accent: string;
  accentForeground: string;
  border: string;
  card: string;
  cardForeground: string;
  ring: string;
}

export interface Theme {
  name: string;
  displayName: string;
  light: ThemeColors;
  dark: ThemeColors;
}

export const themes: Record<string, Theme> = {
  catppuccin: {
    name: "catppuccin",
    displayName: "Catppuccin",
    light: {
      background: "#eff1f5",
      foreground: "#4c4f69",
      primary: "#1e66f5",
      primaryForeground: "#eff1f5",
      secondary: "#ccd0da",
      secondaryForeground: "#4c4f69",
      muted: "#ccd0da",
      mutedForeground: "#7287fd",
      accent: "#dd7878",
      accentForeground: "#eff1f5",
      border: "#dce0e8",
      card: "#e6e9ef",
      cardForeground: "#4c4f69",
      ring: "#1e66f5",
    },
    dark: {
      background: "#1e1e2e",
      foreground: "#cdd6f4",
      primary: "#89b4fa",
      primaryForeground: "#1e1e2e",
      secondary: "#313244",
      secondaryForeground: "#cdd6f4",
      muted: "#313244",
      mutedForeground: "#6c7086",
      accent: "#f38ba8",
      accentForeground: "#1e1e2e",
      border: "#313244",
      card: "#181825",
      cardForeground: "#cdd6f4",
      ring: "#89b4fa",
    },
  },
  catppuccinMocha: {
    name: "catppuccinMocha",
    displayName: "Catppuccin Mocha",
    light: {
      background: "#f5e0dc",
      foreground: "#5c5f77",
      primary: "#cba6f7",
      primaryForeground: "#1e1e2e",
      secondary: "#fab387",
      secondaryForeground: "#1e1e2e",
      muted: "#bac2de",
      mutedForeground: "#6c7086",
      accent: "#f9e2af",
      accentForeground: "#1e1e2e",
      border: "#bac2de",
      card: "#f2d5cf",
      cardForeground: "#5c5f77",
      ring: "#cba6f7",
    },
    dark: {
      background: "#1e1e2e",
      foreground: "#cdd6f4",
      primary: "#cba6f7",
      primaryForeground: "#1e1e2e",
      secondary: "#313244",
      secondaryForeground: "#cdd6f4",
      muted: "#313244",
      mutedForeground: "#6c7086",
      accent: "#f9e2af",
      accentForeground: "#1e1e2e",
      border: "#313244",
      card: "#181825",
      cardForeground: "#cdd6f4",
      ring: "#cba6f7",
    },
  },
  nord: {
    name: "nord",
    displayName: "Nord",
    light: {
      background: "#eceff4",
      foreground: "#2e3440",
      primary: "#5e81ac",
      primaryForeground: "#eceff4",
      secondary: "#d8dee9",
      secondaryForeground: "#2e3440",
      muted: "#d8dee9",
      mutedForeground: "#4c566a",
      accent: "#88c0d0",
      accentForeground: "#2e3440",
      border: "#d8dee9",
      card: "#e5e9f0",
      cardForeground: "#2e3440",
      ring: "#5e81ac",
    },
    dark: {
      background: "#2e3440",
      foreground: "#eceff4",
      primary: "#88c0d0",
      primaryForeground: "#2e3440",
      secondary: "#3b4252",
      secondaryForeground: "#eceff4",
      muted: "#3b4252",
      mutedForeground: "#4c566a",
      accent: "#81a1c1",
      accentForeground: "#2e3440",
      border: "#3b4252",
      card: "#3b4252",
      cardForeground: "#eceff4",
      ring: "#88c0d0",
    },
  },
  tokyoNight: {
    name: "tokyoNight",
    displayName: "Tokyo Night",
    light: {
      background: "#d5d6db",
      foreground: "#1a1b26",
      primary: "#2e7de9",
      primaryForeground: "#d5d6db",
      secondary: "#a9b1d6",
      secondaryForeground: "#1a1b26",
      muted: "#a9b1d6",
      mutedForeground: "#444b6a",
      accent: "#bb9af7",
      accentForeground: "#1a1b26",
      border: "#a9b1d6",
      card: "#cbcde0",
      cardForeground: "#1a1b26",
      ring: "#2e7de9",
    },
    dark: {
      background: "#1a1b26",
      foreground: "#c0caf5",
      primary: "#7aa2f7",
      primaryForeground: "#1a1b26",
      secondary: "#24283b",
      secondaryForeground: "#c0caf5",
      muted: "#24283b",
      mutedForeground: "#565f89",
      accent: "#bb9af7",
      accentForeground: "#1a1b26",
      border: "#24283b",
      card: "#16161e",
      cardForeground: "#c0caf5",
      ring: "#7aa2f7",
    },
  },
  dracula: {
    name: "dracula",
    displayName: "Dracula",
    light: {
      background: "#f8f8f2",
      foreground: "#282a36",
      primary: "#bd93f9",
      primaryForeground: "#f8f8f2",
      secondary: "#e9e9e4",
      secondaryForeground: "#282a36",
      muted: "#e9e9e4",
      mutedForeground: "#6272a4",
      accent: "#ff79c6",
      accentForeground: "#282a36",
      border: "#e9e9e4",
      card: "#ffffff",
      cardForeground: "#282a36",
      ring: "#bd93f9",
    },
    dark: {
      background: "#282a36",
      foreground: "#f8f8f2",
      primary: "#bd93f9",
      primaryForeground: "#282a36",
      secondary: "#44475a",
      secondaryForeground: "#f8f8f2",
      muted: "#44475a",
      mutedForeground: "#6272a4",
      accent: "#ff79c6",
      accentForeground: "#282a36",
      border: "#44475a",
      card: "#21222c",
      cardForeground: "#f8f8f2",
      ring: "#bd93f9",
    },
  },
  github: {
    name: "github",
    displayName: "GitHub",
    light: {
      background: "#ffffff",
      foreground: "#24292f",
      primary: "#0969da",
      primaryForeground: "#ffffff",
      secondary: "#f6f8fa",
      secondaryForeground: "#24292f",
      muted: "#f6f8fa",
      mutedForeground: "#656d76",
      accent: "#a6442a",
      accentForeground: "#ffffff",
      border: "#d0d7de",
      card: "#ffffff",
      cardForeground: "#24292f",
      ring: "#0969da",
    },
    dark: {
      background: "#0d1117",
      foreground: "#e6edf3",
      primary: "#58a6ff",
      primaryForeground: "#0d1117",
      secondary: "#21262d",
      secondaryForeground: "#e6edf3",
      muted: "#21262d",
      mutedForeground: "#8b949e",
      accent: "#f78166",
      accentForeground: "#0d1117",
      border: "#30363d",
      card: "#161b22",
      cardForeground: "#e6edf3",
      ring: "#58a6ff",
    },
  },
  rosePine: {
    name: "rosePine",
    displayName: "Rosé Pine",
    light: {
      background: "#faf4ed",
      foreground: "#575279",
      primary: "#907aa9",
      primaryForeground: "#faf4ed",
      secondary: "#f2e9e1",
      secondaryForeground: "#575279",
      muted: "#f2e9e1",
      mutedForeground: "#9893a5",
      accent: "#eb6f92",
      accentForeground: "#faf4ed",
      border: "#f2e9e1",
      card: "#fffaf3",
      cardForeground: "#575279",
      ring: "#907aa9",
    },
    dark: {
      background: "#191724",
      foreground: "#e0def4",
      primary: "#ebbcba",
      primaryForeground: "#191724",
      secondary: "#1f1d2e",
      secondaryForeground: "#e0def4",
      muted: "#1f1d2e",
      mutedForeground: "#6e6a86",
      accent: "#eb6f92",
      accentForeground: "#191724",
      border: "#1f1d2e",
      card: "#191724",
      cardForeground: "#e0def4",
      ring: "#ebbcba",
    },
  },
  gruvbox: {
    name: "gruvbox",
    displayName: "Gruvbox",
    light: {
      background: "#fbf1c7",
      foreground: "#282828",
      primary: "#98971a",
      primaryForeground: "#fbf1c7",
      secondary: "#ebdbb2",
      secondaryForeground: "#282828",
      muted: "#ebdbb2",
      mutedForeground: "#928374",
      accent: "#cc241d",
      accentForeground: "#fbf1c7",
      border: "#d5c4a1",
      card: "#fdf4c1",
      cardForeground: "#282828",
      ring: "#98971a",
    },
    dark: {
      background: "#282828",
      foreground: "#ebdbb2",
      primary: "#b8bb26",
      primaryForeground: "#282828",
      secondary: "#3c3836",
      secondaryForeground: "#ebdbb2",
      muted: "#3c3836",
      mutedForeground: "#928374",
      accent: "#fb4934",
      accentForeground: "#282828",
      border: "#3c3836",
      card: "#1d2021",
      cardForeground: "#ebdbb2",
      ring: "#b8bb26",
    },
  },
  solarized: {
    name: "solarized",
    displayName: "Solarized",
    light: {
      background: "#fdf6e3",
      foreground: "#657b83",
      primary: "#268bd2",
      primaryForeground: "#fdf6e3",
      secondary: "#eee8d5",
      secondaryForeground: "#657b83",
      muted: "#eee8d5",
      mutedForeground: "#93a1a1",
      accent: "#cb4b16",
      accentForeground: "#fdf6e3",
      border: "#93a1a1",
      card: "#fdf6e3",
      cardForeground: "#657b83",
      ring: "#268bd2",
    },
    dark: {
      background: "#002b36",
      foreground: "#839496",
      primary: "#268bd2",
      primaryForeground: "#002b36",
      secondary: "#073642",
      secondaryForeground: "#839496",
      muted: "#073642",
      mutedForeground: "#586e75",
      accent: "#cb4b16",
      accentForeground: "#002b36",
      border: "#073642",
      card: "#002b36",
      cardForeground: "#839496",
      ring: "#268bd2",
    },
  },
};

export const themeNames = Object.keys(themes) as (keyof typeof themes)[];
export const defaultTheme = "github";
export const defaultMode: ThemeMode = "dark";

export function getTheme(themeName: string, mode: ThemeMode): ThemeColors {
  const theme = themes[themeName] || themes[defaultTheme];
  return theme[mode];
}
